version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-server
    image: node:latest
    env_file: .env
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - JWT_ACCESS_KEY=${JWT_ACCESS_KEY}
      - JWT_REFRESH_KEY=${JWT_REFRESH_KEY}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    restart: always
    stdin_open: true
    networks:
      - app-network

  mongo:
    image: mongo:4.2.8
    container_name: mongoDB
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb:
  mongodb_config:
  node_modules:
